const SUPABASE_URL = 'https://mzuysaggtjrzqgyblbgm.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16dXlzYWdndGpyenFneWJsYmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAyNzY1MTMsImV4cCI6MjEwNTg1MjUxM30.4yGd4b3hQxZcBrECOsm3aynEOvjmk3bbEFgd7va3gNU';

window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);